# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instaMeet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instaMeet
pod 'Onboard'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'GoogleMaps'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'GooglePlaces'
pod "WSTagsField"
pod "SwiftChart"

end
